# -*- coding: utf-8 -*-
"""part1_grade_tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4gmmSDKxALDNdqTp-gqQGJfs_jQMrNa
"""

# Raw student data (given)
raw_students = [
    {"name": "  ayesha SHARMA  ", "roll": "101", "marks_str": "88, 72, 95, 60, 78"},
    {"name": "ROHIT verma",       "roll": "102", "marks_str": "55, 68, 49, 72, 61"},
    {"name": "  Priya Nair  ",    "roll": "103", "marks_str": "91, 85, 88, 94, 79"},
    {"name": "karan MEHTA",       "roll": "104", "marks_str": "40, 55, 38, 62, 50"},
    {"name": " Sneha pillai ",    "roll": "105", "marks_str": "75, 80, 70, 68, 85"},
]

# List to store cleaned student data
cleaned_students = []

# Loop through each student and clean data
for student in raw_students:

    # Clean name: remove spaces and convert to title case
    name = student["name"].strip().title()

    # Convert roll number to integer
    roll = int(student["roll"])

    # Convert marks_str to list of integers
    marks = student["marks_str"].split(", ")
    marks = [int(m) for m in marks]

    # Validate name: each word should contain only alphabets
    words = name.split()
    is_valid = True

    for word in words:
        if not word.isalpha():
            is_valid = False
            break

    # Print validation result
    if is_valid:
        print(f"{name} → ✓ Valid name")
    else:
        print(f"{name} → ✗ Invalid name")

    # Store cleaned data
    cleaned_students.append({
        "name": name,
        "roll": roll,
        "marks": marks
    })

    # Print formatted profile card
    print("================================")
    print(f"Student : {name}")
    print(f"Roll No : {roll}")
    print(f"Marks   : {marks}")
    print("================================")

# Find student with roll number 103
for student in cleaned_students:
    if student["roll"] == 103:
        print("\nSpecial Output for Roll 103:")
        print(student["name"].upper())
        print(student["name"].lower())