# -*- coding: utf-8 -*-
"""part1_grade_tracker

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a4gmmSDKxALDNdqTp-gqQGJfs_jQMrNa
"""

# Raw student data (given)
raw_students = [
    {"name": "  ayesha SHARMA  ", "roll": "101", "marks_str": "88, 72, 95, 60, 78"},
    {"name": "ROHIT verma",       "roll": "102", "marks_str": "55, 68, 49, 72, 61"},
    {"name": "  Priya Nair  ",    "roll": "103", "marks_str": "91, 85, 88, 94, 79"},
    {"name": "karan MEHTA",       "roll": "104", "marks_str": "40, 55, 38, 62, 50"},
    {"name": " Sneha pillai ",    "roll": "105", "marks_str": "75, 80, 70, 68, 85"},
]

# List to store cleaned student data
cleaned_students = []

# Loop through each student and clean data
for student in raw_students:

    # Clean name: remove spaces and convert to title case
    name = student["name"].strip().title()

    # Convert roll number to integer
    roll = int(student["roll"])

    # Convert marks_str to list of integers
    marks = student["marks_str"].split(", ")
    marks = [int(m) for m in marks]

    # Validate name: each word should contain only alphabets
    words = name.split()
    is_valid = True

    for word in words:
        if not word.isalpha():
            is_valid = False
            break

    # Print validation result
    if is_valid:
        print(f"{name} → ✓ Valid name")
    else:
        print(f"{name} → ✗ Invalid name")

    # Store cleaned data
    cleaned_students.append({
        "name": name,
        "roll": roll,
        "marks": marks
    })

    # Print formatted profile card
    print("================================")
    print(f"Student : {name}")
    print(f"Roll No : {roll}")
    print(f"Marks   : {marks}")
    print("================================")

# Find student with roll number 103
for student in cleaned_students:
    if student["roll"] == 103:
        print("\nSpecial Output for Roll 103:")
        print(student["name"].upper())
        print(student["name"].lower())

# Given data
student_name = "Ayesha Sharma"
subjects = ["Math", "Physics", "CS", "English", "Chemistry"]
marks = [88, 72, 95, 60, 78]

print(f"\nStudent: {student_name}\n")

# -------- PART 1: Subject-wise grades --------
print("Subject-wise Performance:")

for i in range(len(subjects)):
    score = marks[i]

    # Grade calculation using conditionals
    if score >= 90:
        grade = "A+"
    elif score >= 80:
        grade = "A"
    elif score >= 70:
        grade = "B"
    elif score >= 60:
        grade = "C"
    else:
        grade = "F"

    print(f"{subjects[i]} : {score} → {grade}")

# -------- PART 2: Total, Average, Highest, Lowest --------

# Total marks
total = sum(marks)

# Average marks (rounded to 2 decimal places)
average = round(total / len(marks), 2)

# Highest scoring subject
max_marks = max(marks)
max_index = marks.index(max_marks)

# Lowest scoring subject
min_marks = min(marks)
min_index = marks.index(min_marks)

print("\nSummary:")
print(f"Total Marks   : {total}")
print(f"Average Marks : {average}")
print(f"Highest       : {subjects[max_index]} ({max_marks})")
print(f"Lowest        : {subjects[min_index]} ({min_marks})")

# -------- PART 3: While loop for adding new subjects --------

print("\n--- Add New Subjects ---")

new_count = 0  # counter for new subjects

while True:
    subject = input("Enter subject name (or type 'done' to stop): ")

    if subject.lower() == "done":
        break

    marks_input = input("Enter marks (0-100): ")

    # Validate marks input
    if not marks_input.isdigit():
        print("Invalid input! Please enter a number.")
        continue

    score = int(marks_input)

    if score < 0 or score > 100:
        print("Marks should be between 0 and 100.")
        continue

    # Add valid entry
    subjects.append(subject)
    marks.append(score)
    new_count += 1

print(f"\nNew subjects added: {new_count}")

# Updated average after adding new subjects
new_average = round(sum(marks) / len(marks), 2)
print(f"Updated Average: {new_average}")

# Complete data of the class provided
class_data = [
    ("Ayesha Sharma",  [88, 72, 95, 60, 78]),
    ("Rohit Verma",    [55, 68, 49, 72, 61]),
    ("Priya Nair",     [91, 85, 88, 94, 79]),
    ("Karan Mehta",    [40, 55, 38, 62, 50]),
    ("Sneha Pillai",   [75, 80, 70, 68, 85]),
]

print("Name              | Average | Status")
print("----------------------------------------")

pass_count = 0
fail_count = 0

topper_name = ""
topper_avg = 0

total_avg_sum = 0  # calculating the class average for each student

# Loop through each student
for student in class_data:
    name = student[0]
    marks = student[1]

    # Calculate average
    avg = round(sum(marks) / len(marks), 2)
    total_avg_sum += avg

    # Checking pass/fail for each student
    if avg >= 60:
        status = "Pass"
        pass_count += 1
    else:
        status = "Fail"
        fail_count += 1

    # Checking for topper's score
    if avg > topper_avg:
        topper_avg = avg
        topper_name = name

    # Print formatted row
    print(f"{name:<18} | {avg:^7} | {status}")

# -------- Summary --------

# Class average (average of all students' averages)
class_avg = round(total_avg_sum / len(class_data), 2)

print("\nSummary:")
print(f"Passed Students : {pass_count}")
print(f"Failed Students : {fail_count}")
print(f"Class Topper    : {topper_name} ({topper_avg})")
print(f"Class Average   : {class_avg}")

# given essay
essay = "  python is a versatile language. it supports object oriented, functional, and procedural programming. python is widely used in data science and machine learning.  "

# step 1 - removing extra spaces from start and end
clean_essay = essay.strip()
print("Clean essay:")
print(clean_essay)


# step 2 - converting into title case
print("\nTitle case version:")
print(clean_essay.title())


# step 3 - counting how many times 'python' appears
count = clean_essay.count("python")
print("\nNumber of times 'python' appears:")
print(count)


# step 4 - replacing python with Python 🐍
new_text = clean_essay.replace("python", "Python 🐍")
print("\nAfter replacement:")
print(new_text)


# step 5 - splitting into sentences
sent_list = clean_essay.split(". ")
print("\nSentence list:")
print(sent_list)


# step 6 - printing sentences one by one
print("\nSentences one by one:")

num = 1
for s in sent_list:

    # adding dot if not present
    if not s.endswith("."):
        s = s + "."

    print(str(num) + ". " + s)
    num += 1